---
title: Указание ошибок в исключениях
description: Для традиционных программистов C ошибки обычно возвращаются через возвращаемые значения или специальным параметром \ out \, который возвращает код ошибки.
ms.assetid: 85ee217d-6e0b-4160-9cec-a652c1daa9a0
ms.topic: article
ms.date: 05/31/2018
ms.openlocfilehash: 816f63f9378c3f2338c7bed6f6a9b5f785d3e138e4762c355aa1932887fd14c9
ms.sourcegitcommit: e858bbe701567d4583c50a11326e42d7ea51804b
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 08/11/2021
ms.locfileid: "118928920"
---
# <a name="indicate-errors-by-exceptions"></a>Указание ошибок в исключениях

Для традиционных программистов C ошибки обычно возвращаются с помощью возвращаемых значений или специального \[ параметра out \] , который возвращает код ошибки. Это приводит к интерфейсам, реализованным следующим образом:

``` syntax
long sample(...)
{
    ...
    p = new Cbar(...);
    if (p == NULL)
    {
        // cleanup
        ...
        return ERROR_OUTOFMEMORY;
    }
}
```

Проблема с этим подходом заключается в том, что возвращаемые значения RPC являются просто целыми числами. Они не имеют специального смысла как ошибки (Обратите внимание, что [**\_ состояние ошибки \_ t**](/windows/desktop/Midl/error-status-t) не имеет специальной семантики на стороне сервера), что несет важные последствия.

Во-первых, RPC не предупреждает о сбое операции; Он пытается распаковать все \[ входные \] и выходные \[ \] аргументы. Семантика сбоев дескрипторов контекста также отличается. Пакет, возвращаемый клиенту, фактически является пакетом успешного выполнения с кодом ошибки, который скрыт глубоко в пакете. Это также означает, что RPC не использует расширенные сведения об ошибке, поэтому клиентское программное обеспечение часто не может распоразличить место вызова.

Указание ошибок в подпрограммах сервера RPC путем вызова исключений структурированной обработки исключений (SEH) (не C++) является гораздо лучшим подходом. При возникновении исключения SEH управление переходит непосредственно к времени выполнения RPC. Ошибка иногда возникает в подпрограмме, которая не может быть правильно очищена, и должна указывать на ошибку вызывающей стороне. Подпрограмма должна возвращать ошибку вызывающему объекту, которая, в свою очередь, может возвращать ошибку вызывающему объекту и т. д. Однако последняя Серверная подпрограммы в стеке должна вызвать исключение перед возвратом в RPC, чтобы указать RPC на то, что произошла ошибка.

## <a name="related-topics"></a>Связанные темы

<dl> <dt>

[Обработка исключений](exception-handling.md)
</dt> </dl>

 

 